=== Antoooni/RentStation/source/SimpleStationSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.myschema.by/SimpleStationSchema" xmlns:xl="http://www.myschema.by/SimpleStationSchema"
	elementFormDefault="qualified">


	<xs:element name="RentStation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Managers">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Manager">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="RentUnits">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Equipments">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Skis">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="Ski" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="Brand" type="xs:string" />
																						<xs:element name="Category" type="xs:string" />
																						<xs:element name="Price" type="xs:double" />
																					</xs:sequence>
																					<xs:attribute name="isRented" type="xs:boolean" />
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="Snowboards">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="Snowboard" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="Brand" type="xs:string" />
																						<xs:element name="Category" type="xs:string" />
																						<xs:element name="Price" type="xs:double" />
																					</xs:sequence>
																					<xs:attribute name="isRented" type="xs:boolean" />
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																		<xs:attribute name="isRented" type="xs:boolean" />
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="Accessorise">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="SkiAccessories">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="SkiAccessorise"
																				maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="Brand" type="xs:string" />
																						<xs:element name="Name" type="xs:string" />
																						<xs:element name="Colour" type="xs:string" />
																						<xs:element name="Price" type="xs:double" />
																						<xs:element name="Type" type="xs:string" />
																					</xs:sequence>
																					<xs:attribute name="isRented" type="xs:boolean" />
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="SnowboardAccessories">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="SnowboardAccessorise"
																				maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="Brand" type="xs:string" />
																						<xs:element name="Name" type="xs:string" />
																						<xs:element name="Colour" type="xs:string" />
																						<xs:element name="Price" type="xs:double" />
																						<xs:element name="Type" type="xs:string" />
																					</xs:sequence>
																					<xs:attribute name="isRented" type="xs:boolean" />
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="ManagerID" type="xs:string" />
									<xs:attribute name="ManagerName" type="xs:string">
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Antoooni/RentStation/source/RentStation.xml
<?xml version="1.0" encoding="UTF-8"?>
<RentStation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.myschema.by/SimpleStationSchema SimpleStationSchema.xsd"
	xmlns="http://www.myschema.by/SimpleStationSchema">
	<Managers>
		<Manager ManagerID="1122334" ManagerName="Mr.Manager">
			<RentUnits>
				<Equipments>
					<Skis>
						<Ski isRented="false">
							<Brand>Volkl</Brand>
							<Category>CHILD</Category>
							<Price>30.0</Price>
						</Ski>
						<Ski isRented="false">
							<Brand>Fisher</Brand>
							<Category>ADULT</Category>
							<Price>25.0</Price>
						</Ski>
					</Skis>
					<Snowboards>
						<Snowboard isRented="false">
							<Brand>Fisher</Brand>
							<Category>CHILD</Category>
							<Price>20.0</Price>
						</Snowboard>
						<Snowboard isRented="false">
							<Brand>Flow</Brand>
							<Category>ADULT</Category>
							<Price>40.0</Price>
						</Snowboard>
						<Snowboard isRented="false">
							<Brand>Burton</Brand>
							<Category>ADULT</Category>
							<Price>27.5</Price>
						</Snowboard>
					</Snowboards>
				</Equipments>
				<Accessorise>
					<SkiAccessories>
						<SkiAccessorise isRented="false">
							<Brand>gopro</Brand>
							<Name>Hero 4</Name>
							<Colour>black</Colour>
							<Price>25.0</Price>
							<Type>OTHER</Type>
						</SkiAccessorise>
						<SkiAccessorise isRented="false">
							<Brand>Atomic</Brand>
							<Name>gloves</Name>
							<Colour>white</Colour>
							<Price>10.0</Price>
							<Type>CLOTHES</Type>
						</SkiAccessorise>
					</SkiAccessories>
					<SnowboardAccessories>
						<SnowboardAccessorise isRented="false">
							<Brand>Trespass</Brand>
							<Name>no name</Name>
							<Colour>green</Colour>
							<Price>5.0</Price>
							<Type>PROTECTION</Type>
						</SnowboardAccessorise>
					</SnowboardAccessories>
				</Accessorise>
			</RentUnits>
		</Manager>
	</Managers>
</RentStation>
